<Project>
  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <NuGetAuditMode>all</NuGetAuditMode>
    <RestoreEnablePackagePruning>true</RestoreEnablePackagePruning>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true' Or '$(GITHUB_ACTIONS)' == 'true'">true</ContinuousIntegrationBuild>
    <RepositoryUrl>https://github.com/rodri-oliveira-dev/Dapper.TypedParameters</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <Authors>Rodrigo de Oliveira</Authors>
    <Copyright>Copyright (c) 2026 Rodrigo de Oliveira</Copyright>
  </PropertyGroup>
</Project>
